"""
  Default parameter values.

"""
GAUSSIAN_FILTER_SIGMA = 1.5
CC_SCALE_MAX = 2.0
CC_SCALE_MIN = 0.15
VERTICAL_SMOOTHING_MULTIPLIER = 0.75
HORIZONTAL_SMOOTHING_MULTIPLIER = 0.75
MINIMUM_TEXT_SIZE_THRESHOLD=7
MAXIMUM_VERTICAL_SPACE_VARIANCE=5.0

